# Xray Web Manager 配置文件

server:
    host: 0.0.0.0
    port: "9098"
xray:
    api_addr: localhost:10085
    balancer_tag: balancer
auth:                    # 新增：可选 Basic Auth
  username: "admin"       # 不设置则不启用认证
  password: "200"